name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - uses: actions/cache@v3
        with:
          path: |
            .yarn
            node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn workspaces foreach run check
