name: Docker

on:
  push:
    branches: ['main']

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_REPO}}/learn
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          tags: escapetech/learn:latest

  k8s-deploy:
    needs: docker-push
    runs-on: ubuntu-latest
    steps:
      - name: kubectl-alpine
        uses: d4nicoder/kubectl-action@v2.0
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
      - name: Rollout learn deployment
        run: kubectl -n ${{ secrets.LEARN_NS }} rollout restart deployment.apps/${{ secrets.LEARN_DEPS }}
